/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Interface;

import java.io.*;

interface MyInterface
{
    public void run();
    public void doIt();
    final int a = 20;
}

public class App implements MyInterface{
    
    public void run(){
        System.out.println("Run bray");
    }

    public void doIt(){
        System.out.println("Doing it");
    }

    public static void doItStatically(){
        System.out.println("Doing it staically");
    }

    public static void main(String[] args) {
        App app = new App();
        app.run();
        app.doIt();
        doItStatically();
        System.out.println(a);
    }
}
