/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LatihanNoDua;

import java.util.function.*;
import java.util.stream.*;
import java.io.*;
import java.util.Arrays;

public class App {

    // Array Exist
    public static void main(String[] args) {
        String[] arr = new String[]{"Hello", "There", "what", "DAY", "iS", "iT"};
        char ch;
        int jumlah;
        int benar = 0;
        int salah = 0;
        for(int i = 0; i < arr.length; i++)
        {
            jumlah = arr[i].length();
            for(int j=0; j < jumlah; j++)
            {
                ch = arr[i].charAt(j);
                if(Character.isLowerCase(ch)){
                    benar += 1;
                }
                else{
                    salah += 1;
                }
                if(benar == jumlah){
                    System.out.print(arr[i]);
                }
            }
            benar = 0;
            salah = 0;
        }
    }
    
}
