/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package objectoriented;

public class App {

    public static void main(String[] args) {
        Bicycle bike1 = new Bicycle();
        Bicycle bike2 = new Bicycle();

        bike1.changeCadence(50);
        bike1.speedUp(10);
        bike1.changeGear(2);
        bike1.printStates();

        bike2.changeCadence(30);
        bike2.speedUp(10);
        bike2.changeGear(2);
        bike2.changeCadence(20);
        bike2.speedUp(10);
        bike2.changeGear(3);
        bike2.applyBrakes(5);
        bike2.printStates();
    }

}
