/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Factorypattern;

public class App {

    public static void main(String[] args) {
        ShapeFactory shapeFactory = new ShapeFactory();

        // ambil objek dari circle
        Shape shape1 = shapeFactory.getShape("CIRCLE");

        // panggil draw method circle 
        shape1.draw();

        // ambil objek dari rectangle
        Shape shape2 = shapeFactory.getShape("RECTANGLE");

        // panggil draw method rectangle
        shape2.draw();

        // ambil objek dari square
        Shape shape3 = shapeFactory.getShape("SQUARE");

        // panggil draw method square
        shape3.draw();
    }
}
