/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mvcpattern;

import main.java.Mvcpattern.*;

public class App {
    public static void main(String[] args) {

        Students model = retriveStudentsFromDatabase();
        
        StudentsView view = new StudentsView();

        StudentsController controller = new StudentsController(model, view);

        controller.updateView();

        controller.setStudentsName("Syamil");

        controller.updateView();

    }

    private static Students retriveStudentsFromDatabase()
    {
        Students student = new Students();
        student.setName("Paul");
        student.setRollNo("201");
        return student;
    }
}
