/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Singletonpattern;

import main.java.Singletonpattern.SingleObject;

public class App {
    public static void main(String[] args) {
        SingleObject object = SingleObject.getInstance();
        object.showMessage();
    }
}
