/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HigherOrderFunction;

import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        
        // List<String> list = new ArrayList<>();
        List<String> list = new ArrayList<>();
        list.add("one");
        list.add("two");
        list.add("three");

        Collections.sort(list, (String a, String b) -> {
            return a.compareTo(b);
        });

        System.out.println(list);

    }

}
