/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package json;

import java.io.IOException;
import java.io.StringWriter;

import org.json.simple.JSONObject;

public class App {

    public static void main(String[] args) throws IOException {
        JSONObject obj = new JSONObject();
        
        obj.put("name","foo");
        obj.put("num",new Integer(100));
        obj.put("balance",new Double(100.21));
        obj.put("is_vip",new Boolean(true));

        // output json on Objek 
        System.out.print("Json Outout objek :");
        System.out.println(obj);
        
        StringWriter out = new StringWriter();
        obj.writeJSONString(out);

        System.out.print("Json toString() :");
        String jsonText = out.toString();
        System.out.println(jsonText);

    }
}
